# Generated by Django 6.1.1 on 2026-09-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='agree_privacy_policy',
            field=models.BooleanField(default=False, verbose_name='개인정보 수집 및 이용 동의'),
        ),
    ]
