# Generated by Django 6.1.1 on 2026-10-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_agree_privacy_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='일자리플랫폼', max_length=50, verbose_name='사이트 이름')),
                ('logo', models.ImageField(blank=True, help_text='상단 헤더에 표시될 로고 이미지 (추천: PNG, 가로형 이미지)', null=True, upload_to='site_logo/', verbose_name='로고 이미지')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='최종 수정일')),
            ],
            options={
                'verbose_name': '사이트 기본 설정',
                'verbose_name_plural': '사이트 기본 설정',
            },
        ),
    ]
