# Generated by Django 6.1.1 on 2026-09-29 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='공고 제목')),
                ('category', models.CharField(choices=[('construction', '건설/토목'), ('manufacturing', '제조/가공'), ('agriculture', '농어업/축산'), ('restaurant', '식당/조리/보조'), ('cleaning', '청소/미화')], max_length=50, verbose_name='모집 직종')),
                ('location', models.CharField(max_length=100, verbose_name='근무 지역 (예: 서울 강남구)')),
                ('salary', models.CharField(max_length=100, verbose_name='급여 조건 (예: 일당 15만원 / 월 350만원)')),
                ('visa_requirement', models.CharField(choices=[('all', '전체 비자 가능 (F계열 등)'), ('f2_f4_f5_f6', 'F-2, F-4, F-5, F-6 (동포 비자)'), ('e9', 'E-9 (비전문취업)'), ('h2', 'H-2 (방문취업)')], default='all', max_length=50, verbose_name='지원 가능 비자')),
                ('description', models.TextField(verbose_name='상세 업무 내용 및 자격 요건')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='긴급 구인 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('deadline', models.DateField(verbose_name='마감일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자(기업/관리자)')),
            ],
            options={
                'verbose_name': '구인 공고',
                'verbose_name_plural': '구인 공고 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
