# Generated by Django 6.1.1 on 2026-09-30 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='예: 건설/현장, 제조/생산, 식당/서빙', max_length=50, unique=True, verbose_name='업종명')),
                ('slug', models.SlugField(allow_unicode=True, help_text='URL 주소에 사용될 식별자 (예: construction, restaurant)', unique=True, verbose_name='슬러그')),
                ('image', models.ImageField(blank=True, help_text='메인 화면 업종 카드에 표시될 4:3 비율의 이미지', null=True, upload_to='categories/', verbose_name='업종 대표 이미지')),
                ('description', models.TextField(blank=True, help_text='업종에 대한 간단한 설명', verbose_name='업종 설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
            ],
            options={
                'verbose_name': '업종 카테고리',
                'verbose_name_plural': '업종 카테고리 목록',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='author',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='visa_requirement',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='company_name',
            field=models.CharField(default='회사', max_length=100, verbose_name='업체명'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobposting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='job_postings/', verbose_name='공고 대표 이미지'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='체크 시 메인/상세 화면에 [마감] 뱃지가 표시됩니다.', verbose_name='마감 여부'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='pay',
            field=models.CharField(default='미지정', help_text='예: 일급 15만원, 월급 300만원', max_length=100, verbose_name='급여 조건'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobposting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='작성일'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='description',
            field=models.TextField(verbose_name='상세 내용'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='is_urgent',
            field=models.BooleanField(default=False, help_text='체크 시 메인/상세 화면에 [급구] 뱃지가 표시됩니다.', verbose_name='급구 여부'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='location',
            field=models.CharField(max_length=200, verbose_name='근무지 위치'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_postings', to='jobs.category', verbose_name='업종 카테고리'),
        ),
    ]
