# Generated by Django 6.1.1 on 2026-09-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_category_remove_jobposting_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order_num', 'name'], 'verbose_name': '업종 카테고리', 'verbose_name_plural': '업종 카테고리 목록'},
        ),
        migrations.AddField(
            model_name='category',
            name='order_num',
            field=models.IntegerField(default=0, help_text='낮은 숫자가 먼저 표시됩니다 (예: 1, 2, 3...)', verbose_name='정렬 순서'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='메인 화면 업종 카드에 표시될 이미지', null=True, upload_to='categories/', verbose_name='업종 대표 이미지'),
        ),
    ]
