# Generated by Django 6.1.1 on 2026-10-08 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_category_options_remove_category_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobposting',
            options={'ordering': ['-priority_order', '-created_at'], 'verbose_name': '구인 공고', 'verbose_name_plural': '구인 공고 목록'},
        ),
        migrations.AddField(
            model_name='jobposting',
            name='is_vip',
            field=models.BooleanField(default=False, help_text='추후 결제 시스템 확장용 필드', verbose_name='VIP/유료 공고 여부'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='priority_order',
            field=models.IntegerField(default=0, help_text='1~8 입력 시 해당 위치에 우선 배치됩니다. (0은 기본 최신순 정렬)', verbose_name='고정 순서 (1~8)'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='긴급구인 등 동영상 첨부 시 입력 (예: https://www.youtube.com/watch?v=...)', null=True, verbose_name='유튜브 동영상 URL'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='예: 경비/보안, 미화/청소, 긴급구인', max_length=50, unique=True, verbose_name='업종명'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=0, help_text='메인 화면 카테고리 표시 순서 (작은 숫자가 먼저 나옴)', verbose_name='정렬 순서'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='업체명'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='상세 내용'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='체크 시 [마감] 뱃지가 표시됩니다.', verbose_name='마감 여부'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='is_urgent',
            field=models.BooleanField(default=False, help_text='체크 시 [급구] 뱃지가 표시됩니다.', verbose_name='급구 여부'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='근무지 위치'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='pay',
            field=models.CharField(blank=True, default='', help_text='예: 일급 15만원, 월급 300만원', max_length=100, verbose_name='급여 조건'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='title',
            field=models.CharField(help_text='예: 강남구 주상복합 아파트 보안요원 모집', max_length=200, verbose_name='검색용 제목'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='지원자 이름')),
                ('phone_number', models.CharField(max_length=20, verbose_name='전화번호')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='지원 일시')),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.jobposting', verbose_name='지원 공고')),
            ],
            options={
                'verbose_name': '지원 내역',
                'verbose_name_plural': '지원 내역 목록',
                'ordering': ['-applied_at'],
            },
        ),
    ]
